/**
 * Regenerates the demo's sample page and its recorded transcription.
 *
 * The hosted demo has no server, so it cannot call a model. To still show the
 * page-reading path end to end, it ships one real page image together with the
 * transcription a real model produced for it. Everything after transcription
 * (MathML, speech, review flags, export, history) then runs live in the browser.
 *
 * This script is how that pair is made, so it can be checked and re-run:
 *   1. typeset a short worksheet with temml and screenshot it as a PNG;
 *   2. send the PNG through the app's own Ollama provider, several times, and
 *      keep the best run by a fixed rule (see below);
 *   3. write the image to public/sample/ and the transcription to src/demo-sample.ts.
 *
 * Usage: npx tsx tools/make-demo-sample.ts   (needs Ollama running with the model pulled)
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import temml from 'temml';
import { chromium } from 'playwright';
import { OllamaProvider } from '../server/ollama.js';

const MODEL = process.env.OLLAMA_MODEL ?? 'qwen2.5vl:7b';
const RUNS = 3;
const OUT_IMAGE = path.join('public', 'sample', 'worksheet.png');
const OUT_TS = path.join('src', 'demo-sample.ts');

const math = (latex: string) => temml.renderToString(latex, { displayMode: true });

const page = `<!doctype html><html><head><meta charset="utf-8"><style>
  body { margin: 0; background: #fff; color: #111; font: 17px/1.55 Georgia, 'Times New Roman', serif; }
  main { width: 680px; padding: 48px 56px; }
  h1 { font-size: 22px; margin: 0 0 4px; } .sub { color: #444; margin: 0 0 22px; }
  ol { padding-left: 22px; } li { margin: 0 0 14px; }
  math[display="block"] { margin: 8px 0 4px; font-size: 21px; }
</style></head><body><main>
  <h1>Worksheet 4: Motion and energy</h1>
  <p class="sub">Physics 101. Show your working for every question.</p>
  <ol>
    <li>A ball is thrown straight up with initial speed u. Its height after t seconds is
      ${math('h = ut - \\frac{1}{2}gt^{2}')}</li>
    <li>Write the kinetic energy of a mass m moving at speed v.
      ${math('E_k = \\frac{1}{2}mv^{2}')}</li>
    <li>Find when the ball lands by solving h = 0 with the quadratic formula.
      ${math('t = \\frac{-b \\pm \\sqrt{b^{2} - 4ac}}{2a}')}</li>
    <li>Photosynthesis stores energy from light. Balance the equation.
      ${math('6CO_{2} + 6H_{2}O \\rightarrow C_{6}H_{12}O_{6} + 6O_{2}')}</li>
  </ol>
</main></body></html>`;

async function main(): Promise<void> {
  mkdirSync(path.dirname(OUT_IMAGE), { recursive: true });

  const browser = await chromium.launch({ channel: process.env.PLAYWRIGHT_CHANNEL ?? 'msedge' });
  try {
    const tab = await browser.newPage({ viewport: { width: 792, height: 720 }, deviceScaleFactor: 1.5 });
    await tab.setContent(page);
    await tab.locator('main').screenshot({ path: OUT_IMAGE });
  } finally {
    await browser.close();
  }

  // The model's output varies between runs (temperature 0.1), so record several
  // and keep the best by a fixed, stated rule rather than by eye: most formulas
  // that convert without review, then most LaTeX commands (\frac, \sqrt...) as
  // opposed to plain-text notation like "1/2" or "sqrt(". The choice is recorded
  // in the sample and shown to the demo's viewers.
  const base64 = readFileSync(OUT_IMAGE).toString('base64');
  const provider = new OllamaProvider(MODEL);
  const score = (formulas: { latex: string; needsReview: boolean }[]) => [
    formulas.filter((formula) => !formula.needsReview).length,
    formulas.reduce((sum, formula) => sum + (formula.latex.match(/\\[a-zA-Z]+/g)?.length ?? 0), 0),
  ];
  const better = (a: number[], b: number[]) => a[0] !== b[0] ? a[0] > b[0] : a[1] > b[1];

  let result = await provider.remediateImage(base64, 'image/png');
  console.log(`run 1: ${result.formulas.map((f) => f.latex).join('  |  ')}`);
  for (let run = 2; run <= RUNS; run++) {
    const candidate = await provider.remediateImage(base64, 'image/png');
    console.log(`run ${run}: ${candidate.formulas.map((f) => f.latex).join('  |  ')}`);
    if (better(score(candidate.formulas), score(result.formulas))) result = candidate;
  }

  const sample = {
    model: MODEL,
    runs: RUNS,
    recordedAt: new Date().toISOString().slice(0, 10),
    fileName: 'worksheet-4.png',
    image: 'sample/worksheet.png',
    /** How many formulas the page really has, so the demo can say what the model missed. */
    formulasOnPage: 4,
    originalText: result.originalText,
    latex: result.formulas.map((formula) => formula.latex),
  };

  writeFileSync(
    OUT_TS,
    `/**
 * A real page and the transcription a real model produced for it, for the
 * demo's "Try a sample page". Generated by tools/make-demo-sample.ts; do not
 * edit by hand. Only transcription is recorded: MathML, speech and review
 * flags are derived live from this LaTeX, exactly as for an upload.
 */
export const DEMO_SAMPLE = ${JSON.stringify(sample, null, 2)} as const;
`,
  );

  console.log(`Wrote ${OUT_IMAGE} and ${OUT_TS}: best of ${RUNS} runs with ${MODEL}, ${sample.latex.length} formulas.`);
  for (const latex of sample.latex) console.log('  ', latex);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
