
import { ChangeDetectionStrategy, Component, inject, signal, WritableSignal } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { GeminiService, RemediationResult } from './services/gemini.service';

// FIX: Corrected typo in the 'error' string literal.
type Status = 'idle' | 'loading' | 'success' | 'error';

// Declare pdfjsLib to inform TypeScript that it's loaded globally from a script tag.
declare const pdfjsLib: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  private geminiService = inject(GeminiService);
  public sanitizer = inject(DomSanitizer);

  status: WritableSignal<Status> = signal('idle');
  remediationResult: WritableSignal<RemediationResult> = signal({ formulas: [], originalText: '' });
  errorMessage: WritableSignal<string> = signal('');
  uploadedImage: WritableSignal<string | null> = signal(null);

  constructor() {
    // pdfjsLib is loaded from a script tag in index.html. We must configure its worker.
    if (typeof pdfjsLib !== 'undefined') {
      pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@4.4.168/build/pdf.worker.min.mjs`;
    } else {
        console.error('pdf.js library not loaded. PDF processing will fail.');
    }
  }

  async handleFileChange(event: Event): Promise<void> {
    const input = event.target as HTMLInputElement;
    if (!input.files || input.files.length === 0) {
      return;
    }

    const file = input.files[0];
    const allowedTypes = ['image/png', 'image/jpeg', 'image/webp', 'application/pdf'];
    if (!allowedTypes.includes(file.type)) {
      this.errorMessage.set('Invalid file type. Please upload a PDF, PNG, JPG, or WEBP file.');
      this.status.set('error');
      return;
    }
    
    this.status.set('loading');

    try {
      let imageDetails: { base64String: string, mimeType: string };

      if (file.type === 'application/pdf') {
        imageDetails = await this.pdfToImageBase64(file);
      } else {
        imageDetails = await this.fileToBase64(file);
      }
      
      const { base64String, mimeType } = imageDetails;
      this.uploadedImage.set(base64String);

      const result = await this.geminiService.remediateImage(base64String.split(',')[1], mimeType);

      if (result.formulas && result.formulas.length > 0) {
        this.remediationResult.set(result);
        this.status.set('success');
      } else {
        this.errorMessage.set('Gemini could not find any formulas in the file. Please try a different one.');
        this.status.set('error');
      }
    } catch (error) {
      console.error(error);
      const message = error instanceof Error ? error.message : 'An unknown error occurred.';
      this.errorMessage.set(`Failed to process file. ${message}`);
      this.status.set('error');
    }
  }

  reset(): void {
    this.status.set('idle');
    this.remediationResult.set({ formulas: [], originalText: '' });
    this.errorMessage.set('');
    this.uploadedImage.set(null);
  }

  copyToClipboard(text: string): void {
    navigator.clipboard.writeText(text).catch(err => {
      console.error('Failed to copy text: ', err);
    });
  }

  private sanitizeForLatex(text: string): string {
    return text
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/&/g, '\\&')
      .replace(/%/g, '\\%')
      .replace(/\$/g, '\\$')
      .replace(/#/g, '\\#')
      .replace(/_/g, '\\_')
      .replace(/{/g, '\\{')
      .replace(/}/g, '\\}')
      .replace(/~/g, '\\textasciitilde{}')
      .replace(/\^/g, '\\textasciicircum{}');
  }

  exportToLatex(): void {
    const result = this.remediationResult();
    if (!result.formulas && !result.originalText) {
      return;
    }

    const header = `\\documentclass{article}
\\usepackage[utf8]{inputenc}
\\usepackage{amsmath}
\\usepackage{graphicx}
\\usepackage{geometry}
\\geometry{a4paper, margin=1in}
\\title{Remediated Document}
\\author{Generated by Formula Accessibility Remediator}
\\date{\\today}

\\begin{document}
\\maketitle
`;

    const imageSection = `\\section*{Original Page Image}
\\begin{figure}[h!]
\\centering
\\includegraphics[width=\\textwidth,height=\\textheight,keepaspectratio]{original_page_image.png}
\\caption{The original uploaded document page.}
\\end{figure}
\\clearpage
`;

    const textSection = result.originalText 
      ? `\\section*{Extracted Text Content}
${this.sanitizeForLatex(result.originalText)}
\\clearpage
`
      : '';

    const formulaSection = result.formulas.length > 0
      ? `\\section*{Remediated Formulas}
${result.formulas.map((formula, index) => {
        const sanitizedDescription = this.sanitizeForLatex(formula.description);
        return `\\subsection*{Formula ${index + 1}}
\\subsubsection*{Description}
${sanitizedDescription}

\\subsubsection*{LaTeX}
\\[
${formula.latex}
\\]
\\hrulefill`;
      }).join('\n\n')}
` 
      : '';

    const footer = `
\\end{document}
`;

    const latexContent = header + imageSection + textSection + formulaSection + footer;
    const blob = new Blob([latexContent], { type: 'text/latex' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'remediated-document.tex';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  private fileToBase64(file: File): Promise<{ base64String: string, mimeType: string }> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => resolve({ base64String: reader.result as string, mimeType: file.type });
      reader.onerror = error => reject(error);
    });
  }

  private pdfToImageBase64(file: File): Promise<{ base64String: string, mimeType: string }> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsArrayBuffer(file);
      reader.onload = async () => {
        try {
          if (!reader.result) {
            return reject(new Error('Failed to read PDF file.'));
          }
          const pdfData = new Uint8Array(reader.result as ArrayBuffer);
          const pdf = await pdfjsLib.getDocument({ data: pdfData }).promise;
          const page = await pdf.getPage(1); // Process the first page
          const viewport = page.getViewport({ scale: 2.0 }); // Use a higher scale for better resolution
          const canvas = document.createElement('canvas');
          const context = canvas.getContext('2d');
          if (!context) {
            return reject(new Error('Could not create canvas context.'));
          }
          canvas.height = viewport.height;
          canvas.width = viewport.width;
          await page.render({ canvasContext: context, viewport: viewport }).promise;
          
          // Convert canvas to PNG for consistency and quality
          const mimeType = 'image/png';
          const base64String = canvas.toDataURL(mimeType);
          resolve({ base64String, mimeType });
        } catch (error) {
          console.error('Error processing PDF:', error);
          reject(new Error('Could not process the PDF file. It might be corrupted or protected.'));
        }
      };
      reader.onerror = error => reject(error);
    });
  }
}
