/**
 * A real page and the transcription a real model produced for it, for the
 * demo's "Try a sample page". Generated by tools/make-demo-sample.ts; do not
 * edit by hand. Only transcription is recorded: MathML, speech and review
 * flags are derived live from this LaTeX, exactly as for an upload.
 */
export const DEMO_SAMPLE = {
  "model": "qwen2.5vl:7b",
  "runs": 3,
  "recordedAt": "2026-09-27",
  "fileName": "worksheet-4.png",
  "image": "sample/worksheet.png",
  "formulasOnPage": 4,
  "originalText": "Worksheet 4: Motion and energy\nPhysics 101. Show your working for every question.\n\n1. A ball is thrown straight up with initial speed u. Its height after t seconds is\n\nh = ut - 1/2gt^2\n\n2. Write the kinetic energy of a mass m moving at speed v.\n\nEk = 1/2mv^2\n\n3. Find when the ball lands by solving h = 0 with the quadratic formula.\n\n t = (-b ± sqrt(b^2 - 4ac)) / 2a\n\n4. Photosynthesis stores energy from light. Balance the equation.\n\n6CO2 + 6H2O → C6H12O6 + 6O2",
  "latex": [
    "h = ut - \\frac{1}{2}gt^2",
    "E_k = \\frac{1}{2}mv^2",
    "t = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}"
  ]
} as const;
